modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Pathing-the-way/issues"
license="MIT"

[[mods]]
modId="pathingtheway"
version="${file.jarVersion}"
displayName="Pathing The Way"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pathing-the-way"
authors="Mrbysco, ShyNieke"
description='''
This mod allows you to use an assortment of tools to transform blocks into other blocks by right clicking as configured.
'''
[[dependencies.pathingtheway]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.pathingtheway]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"