modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/Pathing-the-way/issues"
license="MIT"

[[mods]]
modId="pathingtheway"
version="${file.jarVersion}"
displayName="Pathing The Way"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pathing-the-way"
authors="Mrbysco, ShyNieke"
description='''
This mod allows you to use an assortment of tools to transform blocks into other blocks by right clicking as configured.
'''
[[dependencies.pathingtheway]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.pathingtheway]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"